name: AntiCheat
main: me.Haeseke1.AntiCheat.Main.Main
version: 1.0
author: [KingPieter,Haeseke1]
commands:
 AntiCheat:
  permission: Anti_Cheat.commands
  aliases: [ac,anticheat]
  description: Main command of the plugin